In [13]:
import numpy as np

points = np.array([1, 1, 2, 2, 3, 3, 4, 4])
points = points.reshape((int(len(points)/2)), 2)
print(points)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [14]:
print(0<1<2)

True


In [16]:
def s(x, y):
    return np.array([x, y])

points = np.array([[1, 1], [2, 2], [3, 3]])
print(s(points))

TypeError: s() missing 1 required positional argument: 'y'

In [12]:
class Foo:
    def __init__(self, a):
        self.a = a
        
    def hi(self, g):
        print('hi')
        self.a = g
        
        
foo = Foo(3)
def mary(t):
    foo.a = t

mary(2)
print(foo.a)

2


In [16]:
foo = Foo(4)
hi = foo.hi
hi(3.14)
print(foo.a)

hi
3.14


In [24]:
import numpy as np
np.arange(0, 1, 0.5)

array([0. , 0.5])

In [42]:
A = np.array([[1, 2], [3, 4]]).T
v = np.array([1, 1])
# print(A, v)
A*v

array([[1, 3],
       [2, 4]])

In [43]:
np.matmul(A,v)

array([4, 6])

In [52]:
class A:
    def __init__(self, num):
        self.num = num
        
    def add_three(self):
        self.num += 3
        
        
a = A(3)
b = a
b.add_three()
print(a.num)

6


In [90]:
class Animation:
    def __init__(self, start_frame):
        self.start_frame = start_frame
        
        self.h_parent = None
        self.h_right = None
        self.h_left = None

class AnimationQueue:  # min-heap structure for maintaining sorted list of waiting animations
    '''
        Priority queue for animations waiting to be played next. Implemented by min-heap,
        organized by earliest start_frame of Animations. (Perhaps in the future, can reimplement
        this to be an implicit data-structure; i.e. using an array that simulates the bin. tree
        of the heap).

        root: the Animation which is the root of the heap (earliest start frame).
    '''
    def __init__(self, root):
        self.root = root
        self.leaf = self.root  # leaf node on the bottom level to the most right
        self.next_parent = self.root  # parent node for which next added node will be the child

    def add_node(self, node):  # O(log n), total two main O(log(n)) steps: heapify and bad coding.
        # First we insert it into the next available sport
        node.h_parent = self.next_parent
        self.leaf = node

        if self.next_parent.h_left is None:
            self.next_parent.h_left = node
        else:
            self.next_parent.h_right = node

            # Updating next_parent
            grandparent = self.next_parent.h_parent
            if self.next_parent == grandparent.h_left:
                self.next_parent = grandparent.h_right  # we know this exists since it's one level up
            else:
                self.next_parent = self.left_most_node()  # bad implementation

        self.bubble_up()

    def extract_first(self):
        prev_root = self.root
        prev_leaf = self.leaf

        if prev_leaf.h_parent.h_right == prev_leaf:
            self.leaf = prev_leaf.h_parent.h_left
            self.next_parent = prev_leaf.h_parent
        else:
            self.leaf = self.right_most_node()
            self.next_parent = self.leaf.h_parent.h_left

        return prev_root

    def bubble_up(self):
        node = self.leaf
        while node != self.root and node.start_frame < node.h_parent.start_frame:
            self.switch_nodes(node.h_parent, node)

    def sift_down(self):
        node = self.root

        stop = False
        while not stop:
            if node.start_frame > node.h_left.start_frame:
                self.switch_nodes(node, node.h_left)
            elif node.start_frame > node.h_right.start_frame:
                self.switch_nodes(node, node.h_right)
            else:
                stop = True

    def switch_nodes(self, parent, child):
        if parent == self.root:
            self.root = child
        elif child == self.root:
            self.root = parent

        parents_left = parent.h_left
        parents_right = parent.h_right
        grandparent = parent.h_parent

        childs_left = child.h_left
        childs_right = child.h_right

        if grandparent is not None:
            if grandparent.h_left == parent:
                grandparent.h_left = child
            else:
                grandparent.h_right = child
                
        if childs_right is not None:
            childs_right.h_parent = parent
        
        if childs_left is not None:
            childs_left.h_parent = parent

        parent.h_parent = child
        parent.h_right = childs_right
        parent.h_left = childs_left
        child.h_parent = grandparent
        
        if parents_left == child:
            child.h_left = parent
            child.h_right = parents_right
        else: 
            child.h_right = parents
            child.h_left = parents_left


    # O(log n) stupid methods, but who cares for now
    def left_most_node(self):
        node = self.root
        while node.h_left is not None:
            node = node.h_left

        return node

    def right_most_node(self):
        node = self.root
        while node.h_right is not None:
            node = node.h_right

        return node

In [115]:
root = Animation(3)
queue = AnimationQueue(root)
nodes = [Animation(i) for i in [1, 9, 20, 19, 10, 10, 5, 2, 4]]

queue.add_node(nodes[0])
queue.add_node(nodes[1])
print(queue.root.h_right)

3
None


In [117]:
x = 3
print(2<x<4)

True


In [118]:
def hi(x):
    yield 'cookie'
    x = 2
    
print(hi(3))

<generator object hi at 0x117860c50>


In [121]:
ye = 3 == 3
ye

True

In [125]:
import copy 

class Tree:
    def __init__(self, obj):
        self.obj = obj
        
x = Tree(1)
tree = Tree(x)
tree2 = copy.copy(tree)

print(tree2.obj == x)



True


In [141]:
import numpy as np
print(np.random.randint(0,2))

1


In [143]:
sorted([1,2, 3, -12])

[-12, 1, 2, 3]

In [2]:
def nothing():
    return



None


In [3]:
l = [1, 2]
t = l[1]

2


In [8]:
l = [1, 2, 3, 1, 2, 9, 10, 45, 2, 4]
for i, m in enumerate(l):
    if m % 2 == 0:
        l.remove(m)
        
    print('hi', i, l[i])
        
print(l)

hi 0 1
hi 1 3
hi 2 1
hi 3 9
hi 4 45
hi 5 4
[1, 3, 1, 9, 45, 4]


In [9]:
def f(x, y, z):
    print(x + y + z)
    
    
xy = [1, 2]
f(*xy, 3)

6


In [17]:
class C:
    def __init__(self):
        self.bounds = [1, 2]
    
    def potty(self, d):
        print(d)
        self.bounds[1] = 3
        
        
c = C()
x = c.potty

def f(func, inp):
    func(inp)
    
f(x, 4)
print(c.bounds)

4
[1, 3]


In [15]:
import numpy as np

for i in np.arange(1, 2.3, 0.3):
    print(i)

1.0
1.3
1.6
1.9000000000000001
2.2


In [25]:
def to_rgb(h):
    tuple(int(h[i:i+2], 16) for i in (0, 2, 4))
    
print(to_rgb('#B4FBB8'))

ValueError: invalid literal for int() with base 16: '\\#'

In [32]:
x = lambda d: d

print(callable(x))

True


In [34]:
sum([1, 1])

2

In [129]:
t = 0.95

n = len(draw_time_weights)

draw_time_weights = [0.2, 0.2, 0.2, 0.2, 0.2]
anim_slot = None
running_total = draw_time_weights[0]
for i in range(1, n+1):
    if t < running_total:
        anim_slot = i-1
        break
    elif t == running_total and i==n:
        anim_slot = i-1
        break
        
    running_total += draw_time_weights[i]

endpoints = [running_total-draw_time_weights[anim_slot], running_total]
print(anim_slot, endpoints)

4 [0.8, 1.0]


In [130]:
x = 4
y = x
x += 4
y

4

In [131]:
first_run = [[True for ]]


SyntaxError: invalid syntax (<ipython-input-131-1053c44e729b>, line 1)

In [ ]:
import numpy as np 
import cv2 
# for windows, mac users
from PIL import ImageGrab
# for linux users
# import pyscreenshot as ImageGrab

# four character code object for video writer
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
# video writer object
out = cv2.VideoWriter("output.avi", fourcc, 5.0, (1366, 768))

while True:
    # capture computer screen
    img = ImageGrab.grab()
    # convert image to numpy array
    img_np = np.array(img)
    # convert color space from BGR to RGB
    frame = cv2.cvtColor(img_np, cv2.COLOR_BGR2RGB)
    # show image on OpenCV frame
    cv2.imshow("Screen", frame)
    # write frame to video writer
    out.write(frame)
  
    if cv2.waitKey(1) == 27:
        break

out.release()
cv2.destroyAllWindows()

In [7]:
class C:
    def __init__(self, n):
        self.n = n
        
c = C(3)
d = C(4)

e = c
e = d
e.n = 5

print(c.n)
        

3
